/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseTextarea: typeof import('./components/BaseTextarea.vue')['default']
    CookieConsent: typeof import('./components/CookieConsent.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LazyImage: typeof import('./components/LazyImage.vue')['default']
    LegalLayout: typeof import('./components/LegalLayout.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserRating: typeof import('./components/UserRating.vue')['default']
  }
}
